# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_photomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
